server:
  port: 8002
mybatis:
  mapper-locations:
  #  - classpath: mybatis/mapper/**/*.xml
  type-aliases-package: com.yhj.springcloud.microservicecloud.api.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  application:
    name: microservicecloud-dept
logging:
  level:
    com.yhj.springcloud.mapper: debug


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: yhj-microservicecloud
  company.name: www.yhj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
